# Generated by Django 6.0.2 on 2026-02-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
    ]
