# Generated by Django 6.0.2 on 2026-02-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='product',
        ),
        migrations.AddField(
            model_name='client',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='clients', to='products.product'),
        ),
    ]
