# Generated by Django 6.0.2 on 2026-02-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_product_client_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='product',
            new_name='products',
        ),
    ]
