# Generated by Django 6.0.2 on 2026-02-15 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='members',
        ),
        migrations.AddField(
            model_name='business',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_business', to=settings.AUTH_USER_MODEL),
        ),
    ]
