# Generated by Django 6.0.2 on 2026-02-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_members_business_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='members',
        ),
        migrations.AddField(
            model_name='business',
            name='img',
            field=models.ImageField(blank=True, default='businesses/default.png', upload_to='businesses/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owned_business', to=settings.AUTH_USER_MODEL),
        ),
    ]
