class ErrorType:
    REQUIRED = "REQUIRED"
    INVALID = "INVALID"
    MIN_LENGTH = "MIN_LENGTH"
    MAX_LENGTH = "MAX_LENGTH"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH"