# Generated by Django 6.0.2 on 2026-02-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='products/default.png', upload_to='products/'),
        ),
    ]
